
# Site settings
name: 学思结合
email: 871228582@qq.com
author: wmhello
url: http://wmhello.github.io
resume_site: https://wmhello.github.io/about/
github: https://github.com/wmhello/
baseurl: 
description: 真正决定一个人成就的 不是天分 不是运气 而是严格的自律和高强度的付出
meta_description: 王敏;个人博客;学而不思则罔;思而不学则殆;选择了就不要放弃
motto: 坚持就是最重要的策略.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: wmhello

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9
